# make this push a release at some point

name: Build

on:
  push:
    branches: [ "main" ]
    paths: [ "src/**", "scripts/**", ".github/workflows/build.yml", "package.json", "bun.lockb" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - run: bun i
    - run: bun run build
